-- Deploy postgrest:create_jobs_table to pg

BEGIN;

CREATE TABLE jobs (
    id bigint generated by default as identity primary key,
    country text NOT NULL,
    search_term text NOT NULL,
    title text NOT NULL,
    company text NOT NULL,
    location text NOT NULL,
    state text,
    postal text,
    published_date int NOT NULL,
    created_date int NOT NULL,
    expired boolean NOT NULL,
    source_id int NOT NULL,
    feed_id int NOT NULL,
    remote_location boolean NOT NULL,
    company_rating int NOT NULL,
    company_review_count int NOT NULL,
    company_overview_link text,
    company_id_encrypted text NOT NULL,
    salary_min int,
    salary_max int,
    salary_type text,
    salary_currency text,
    snippet text,
    description text,
    inserted_date timestamp default current_timestamp
);

COMMIT;
